# Generated by Django 5.2.7 on 2025-10-29 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('peso', models.FloatField(help_text='En kilogramos')),
                ('estatura', models.FloatField(help_text='En centímetros')),
                ('imc', models.FloatField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('frecuencia_ultraprocesados', models.CharField(max_length=30)),
                ('consume_frutas_verduras', models.BooleanField()),
                ('desayuna_regularmente', models.BooleanField()),
                ('numero_comidas', models.CharField(max_length=20)),
                ('frecuencia_bebidas_azucaradas', models.CharField(max_length=30)),
                ('frecuencia_grasa_saturada', models.CharField(max_length=30)),
                ('consumo_integrales', models.CharField(max_length=30)),
                ('ejercicio_regular', models.BooleanField()),
                ('estres_cronico', models.BooleanField()),
                ('duerme_bien', models.BooleanField()),
                ('cambios_peso', models.CharField(max_length=20)),
                ('fatiga_frecuente', models.BooleanField()),
                ('problemas_digestivos', models.BooleanField()),
                ('examenes_sangre', models.CharField(max_length=30)),
                ('enfermedades_detectadas', models.TextField(blank=True, help_text='Separadas por comas')),
                ('nivel_riesgo', models.CharField(blank=True, max_length=20)),
                ('puntaje_riesgo', models.IntegerField(blank=True, null=True)),
                ('recomendaciones', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
