# Generated by Django 6.0.3 on 2026-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoserecommendation',
            name='additional_advice',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='glucoserecommendation',
            name='immediate_action',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='glucoserecommendation',
            name='when_to_measure',
            field=models.CharField(max_length=150),
        ),
    ]
